### ISSUE TITLE
Student handbook is not downloadable (link is broken )

### ISSUE THREAD

**Issue by GoogleBiz** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#107]
![Screenshot 2021-10-22 235121](https://user-images.githubusercontent.com/33484506/138508202-b0e94224-45ac-4749-ac64-2cab15525b4e.jpg)

Course Name: AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop

Problem: Student handbook is not downloadable (link is broken )

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by polichtm** [comment]
Removed - downloads are available by using the standard GitHub functionality
rgds
Marcin
