### ISSUE TITLE
Lab - Prepare for deployment of Azure Virtual Desktop (AD DS)

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#108]
# Module: 01
#### Step: 01 Within the Remote Desktop session to az140-dc-vm11, from the Administrator: Windows PowerShell ISE script pane, run the following to eanble TLS 1.2:

Description of issue
There is an error in the path of the registry key in the first line of the PowerShell script in Task 1
Repro steps:

1.New-Item 'HKLM:\SOFTWARE\WOW6432Node\Microsoft.NETFramework\v4.0.30319' -Force | Out-Null 
There is a backslash missing after Microsoft
2.The command line should read:  New-Item 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\\.NETFramework\v4.0.30319' -Force | Out-Null

**Comment by polichtm** [comment]
updated
