### ISSUE TITLE
LAB 02L01 Deploy host pools and session hosts with the Azure portal ADDS #join domain failure

### ISSUE THREAD

**Issue by devops-app** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#109]
Module: 02
Lab/Demo: 02L01
Task: 1
Step: 13

Description of issue
Host will not able to join to adatum.com domain as vNet missing add custom DNS server

Suggestion:
Add 10.0.0.4 as a custom DNS server on az140-adds-vnet11

Repro steps:

1.
1.
1.

**Comment by AustinP00** [comment]
Can validate this works successfully.

![image](https://user-images.githubusercontent.com/53233868/139921173-792acaf9-9b82-442d-9c54-0bc8d43e721d.png)

![image](https://user-images.githubusercontent.com/53233868/139922336-890b8da0-c757-48df-a439-e2362d1876d9.png)

**Comment by polichtm** [comment]
This should be already configured by the template deployed in 
https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Instructions/Labs/LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md

https://github.com/Azure/azure-quickstart-templates/blob/master/application-workloads/active-directory/active-directory-new-domain/nestedtemplates/vnet-with-dns-server.json

rgds
Marcin
