### ISSUE TITLE
LAB 02L02 Implement and manage storage for AVD ADDS missing CopyToPSPath.ps1

### ISSUE THREAD

**Issue by devops-app** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#110]
Module: 02
Lab/Demo: 02L02
Task: 03
Step: 06

Description of issue
Missing .\CopyToPSPath.ps1 file

Suggestion:
Download AzFileHybrid zip file.
https://github.com/Azure-Samples/azure-files-samples/releases/download/v0.2.4/AzFilesHybrid.zip

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
It appears that you're not following the instructions:
Task 3: Enable AD DS authentication for the Azure Storage account
Within the Remote Desktop session to az140-dc-vm11, open another tab in the Microsoft Edge window, navigate to the Azure Files samples GitHub repository, download [the most recent version of the compressed AzFilesHybrid.zip PowerShell module, and extract its content into C:\Allfiles\Labs\02 folder (create the folder if needed).
rgds
Marcin
