### ISSUE TITLE
Cannot modify resource with id because the resource entity provisioning state is not terminal

### ISSUE THREAD

**Issue by sahaszz** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#112]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by sahaszz** [comment]
Module: LAB_01L01_Prepare_for_deployment_of_AVD_AADDS.md

Lab/Demo: Excercise 1: task 2
Step 10: 
**After step 10 deployment is failed.** 

**Details of the error**

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "RequestConflict",
      "message": "Cannot modify resource with id '/subscriptions/1d0e8ca4-64d6-4ddb-9d45-63d1416f056c/resourceGroups/az140-11a-RG/providers/Microsoft.AAD/domainServices/adatum.com' because the resource entity provisioning state is not terminal. Please wait for the provisioning state to become terminal and then retry the request."
    }
  ]
}

what am I doing wrong? Can anyone help me?

**Comment by sahaszz** [comment]
Is there any issue with resource group?

**Comment by polichtm** [comment]
Unfortunately I'm not able to reproduce this issue. Did you retry the deployment? Are other students running into the same issue? If not, then pls reach out to your MCT regarding further assistance
rgds
Marcin
