### ISSUE TITLE
Bastions Additions

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#116]
# Module: 01
Exercise 2, Task 2, Step 6
Description of issue

When creating Bastions, a name is needed under Instance details.  It is also advisable that a small note be added to ensure pop-ups are enabled in the browser.

**Comment by polichtm** [comment]
The name of the Bastion is already specified in the instructions. We'll be adding a note regarding pop-ups...
rgds
Marcin

**Comment by polichtm** [comment]
updated
