### ISSUE TITLE
Remove unneeded item from table

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#118]
# Module: 02
#### Step: 06

Description of issue
There is a table with all the values in, in the table it has a value for Public IP there is no Public IP on the wizard, this needs removing as it causes problems for the delegates looking for an item that is not there. 
Repro steps:

1.Remove Public IP value from table
1.
1.

**Comment by polichtm** [comment]
updated
