### ISSUE TITLE
Change script or add peering

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#119]
# Module: 02
#### Step: 00

Description of issue
This lab creates a new VNet, in the instructions it tells you to use the Bastion to connect to the VM, this is nor possible as there is no Bastion with that VNet,  
Repro steps:

1.Option 1 change script to create a net subnet in the existing Vnet
1.Option 2 add instruction in to enable peering between the two Vnets then the Bastion works.
1.

**Comment by polichtm** [comment]
updated
