### ISSUE TITLE
Lab Dependencies

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#120]
# Module: 04
#### Step: 00

Description of issue
This Lab requires that the lab 03L01 has been completed before it will work properly.
Repro steps:

1.add Lab 03L01 as a dependency the this lab requirements
1.
1.

**Comment by polichtm** [comment]
Hi Paul,
would you mind clarifying what specifically that dependency is?
rgds
Marcin

**Comment by PaulFou** [comment]
Part of lab 3 runs the Azure AD connect and set up the computer join, if this is not done before running lab 4L02 the three host machines do not get added to the group.

So ensuring lab 3 is complete before starting lab 4L02

I've also put forward for skillpipe to alter the manual as they don't have a link in module 3 for the lab.

Regards

Paul
________________________________

**Comment by polichtm** [comment]
Hi Paul,
appreciate the clarification. updated
rgds
Marcin
