### ISSUE TITLE
Rearrange the lab files

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#121]
# Module: 00
#### Step: 00

Description of issue
The lab files are list from 01L01 through to 05L01 with both the ADDS and the AADDS next to each other at the bottom of the first lab page it shows the lab tracks, could the links the the labs be put in the same order, this has caused multiple problems with teaching as the delegates open the wrong labs.
Repro steps:

1. Rearrange the labs on the first page to have all the ADDS labs first then all the AADDS labs second picture
![AZ140 Lab order](https://user-images.githubusercontent.com/22152073/144579639-2d25e265-ad00-46bd-8709-025762dc8442.png)
 attached
1.
1.

**Comment by polichtm** [comment]
Hi Paul,
unfortunately renaming the files might have some undesired downstream consequences.
We're considering alternatives
rgds
Marcin

**Comment by PaulFou** [comment]
The file don't need to be renamed just set out in the same order as you have at the bottom if the page divided into the two different streams.

Regards

Paul
________________________________

**Comment by polichtm** [comment]
Hi Paul,
unfortunately it's not clear to me what specifically you're suggesting.
You're welcome to submit a pull request that would actually contain the suggested change
rgds
Marcin

**Comment by PaulFou** [comment]
Hi,
  The lab instructions are currently list as Lab_01L01 for AADDS followed by Lab_01L01 for ADDS and each section has the AADDS labs followed by the ADDS lab, on the lab instruction page at the bottom it shows the labs separated into the two streams all the ADDS lab then the AADDS labs if the links to the instruction oages could be separated in the same way it would be easier for the delegates.

Hope this makes sense.


Regards

Paul
________________________________

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue

**Comment by polichtm** [comment]
Unfortunately we cannot discount the possibility that there are downstream consequences of modifying the existing folder structure. The labs are currently clearly marked as being part of the Azure AD DS or AD DS track - any additional suggestions regarding further enhancing this approach are welcome
rgds
Marcin
