### ISSUE TITLE
Module 1 - Lab 1 - Task 3 - Step 3

### ISSUE THREAD

**Issue by billy-tarazy** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#122]
# Module: 01 Lab - Prepare for deployment of Azure Virtual Desktop (Azure AD DS)
#### Step: 03

Description of issue: when you try to login with **Student@adatum.com**, it doesn't work, when i checked the Json files, there is no Student@adatum.com creation in the process, also no step to create it in the previous tasks.

Repro steps:

1. I managed to login using aadadmin1@[yourdomain].onmicrosoft.com and i successfully logged in

**Comment by polichtm** [comment]
It appears that you are missing the references to the az140-11_azuredeploydc11.parameters.json file (https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Allfiles/Labs/01/az140-11_azuredeploydc11.parameters.json) used in this module, which includes the credentials for the student account.
Pls let us know if any additional clarification is needed
rgds
Marcin

**Comment by billy-tarazy** [comment]
Not really,
These files are only used in AD DS track, not Azure AD DS track which what I referred to.

Please have a look at the tracks and the instructions, the reference files in Azure AD DS track does not contain student account.

Awaiting your confirmation.

**Comment by polichtm** [comment]
Valid point - updated
rgds
Marcin
