### ISSUE TITLE
LAB_02L02 ADDS  az140-cl-vm11 should be az140-dc-vm11 in task1 step 3

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#123]
# Module: 02
#### Step: 03
Lab - Implement and manage storage for AVD (AD DS)

Description of issue

Repro steps:

2. In the Azure portal, search for and select Virtual machines and, from the Virtual machines blade, select az140-dc-vm11.
3. On the az140-cl-vm11 blade, select Connect, in the drop-down menu, select Bastion, on the Bastion tab of the az140-cl-vm11 | Connect blade, select Use Bastion.

Should be

3. On the az140-cl-vm11 blade, select Connect, in the drop-down menu, select Bastion, on the Bastion tab of the **az140-dc-vm11** | Connect blade, select Use Bastion.

**Comment by polichtm** [comment]
updated
