### ISSUE TITLE
Lab 02L01 - Create and configure host pools and session hosts (Azure AD DS) no Student@Adatum.com account

### ISSUE THREAD

**Issue by davemct** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#124]
# Module: 02
#### Step: 04  When prompted, proivde the following credentials and select **Connect**:

   |Setting|Value|
   |---|---|
   |User Name|**Student@adatum.com**|
   |Password|**Pa55w.rd1234**|

Description of issue
There is no Student account in the Adatum.com Azure Active Directory 

You must use aadadmin1@adatum.com

How does this effect the lab further on?  I don't know.  Do we create or use the Student account later?  It would be fairly straight forward to add it before in Lab 1 if necessary.

**Comment by jubic** [comment]
there's no aadadmin1 either. only aadsyncuser or aduser#
