### ISSUE TITLE
Removing unrequired steps in Module 4 Lab_04L01 ADDS

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#125]
# Module: 04
#### Step: 2-6.9-10 and 11

Description of issue
There are some redundant steps in the lab and also linking to the DC then connecting to VM az140-21-p1-0 is putting and extra layer of virtualization that is not required. 

There will be a need to renumber some of the step because of deleting some items
Repro steps:
1.delete items 2-6

2.delete items 9-10

3.change item 11 from
On the az140-21-p1-0 blade, select Connect, in the drop-down menu, select RDP, on the az140-21-p1-0 | Connect blade, in the IP address dropdown list, select the Private IP address entry, select Download RDP File, and then select Open.
to
In the Azure portal, search for and select Virtual machines and, from the Virtual machines blade, select az140-dc-vm11.
On the az140-21-p1-0 blade, select Connect, in the drop-down menu, select Bastion, on the Bastion tab of the az140-21-p1-0 | Connect blade, select Use Bastion.

**Comment by polichtm** [comment]
Hi Paul,
would you mind clarifying the following?
Your suggested change 3 consists of the following sentences:

"In the Azure portal, search for and select Virtual machines and, from the Virtual machines blade, select az140-dc-vm11.
On the az140-21-p1-0 blade, select Connect, in the drop-down menu, select Bastion, on the Bastion tab of the az140-21-p1-0 | Connect blade, select Use Bastion."

It's not clear to me how exactly selecting the **az140-dc-vm11** blade brings you to the **az140-21-p1-0** blade?

rgds
Marcin

**Comment by PaulFou** [comment]
My apologises, that's me cutting and paste, the first sentence should reference az140-21-p1-0, the whole point us to stop using the az140-dc-vm11 as is just added another layer of connection into the mix.

Regards and Happy Holidays

Paul


________________________________

**Comment by polichtm** [comment]
Hi Paul,
updated
rgds
Marcin

**Comment by PaulFou** [comment]
Hi,
  Having just checked the update it will not work, ex 1 task 1 item 4 should read.

 "On the az140-21-p1-0 blade, select Connect, in the drop-down menu, select Bastion, on the Bastion tab of the az140-21-p1-0 | Connect blade, select Use Bastion."

Connecting with the RDP as you still have in the instructions will fail from the lab pc as it does not have a connection. This was used when you first connected to the DC, by taking out the DC you now use the Bastion instead of the RDP.

Regards

Paul
________________________________

**Comment by polichtm** [comment]
Hi Paul
updated
rgds
Marcin
