### ISSUE TITLE
Lab 02L03, WVDInfra is not available in AADDS

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#13]
# Module: 2
#### Step: 6

AADDS does not have WVDInfra OU

Is this lab only designed for ADDS track? The dependency section says either AADDS or ADDS

**Comment by polichtm** [comment]
Pls see my response to #12 
rgds
Marcin
