### ISSUE TITLE
Lab 02L04, az140-dc-vm11 and WVDInfra do not work for AADDS option

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#14]
# Module: 2
#### Step: 2, 6

The issues in lab 02L03 are here too: lab instructions use az140-dc-vm11 and WVDInfra, which do not work if one takes the AADDS option, although the dependency section states both AADDS and ADDS

**Comment by polichtm** [comment]
Pls see my response to #12 
rgds
Marcin
