### ISSUE TITLE
LAB 0101 AD DS  Please add extra step **import-module AzureAD** between Step 6 & Step 7

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#142]
# Module: 01
#### Step: 06

Lab - Prepare for deployment of Azure Virtual Desktop (AD DS)

Please add extra step **import-module AzureAD** between Step 6 & Step 7

**Comment by polichtm** [comment]
updated
