### ISSUE TITLE
Virtual Machine - Connection Error Bastion - Target machine is unreachable - Azure portal (AD DS)

### ISSUE THREAD

**Issue by ParamRamki** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#143]
# Module: 02
### Task 4 : Configure Azure Virtual Desktop application groups

Description of issue 

While performing this step Module 1  >> Lab 2>> Exercise 1 >> Task 4 >> Step 5, the message was constantly appearing to reconnect the VM. Later the Azure Virtual Desktop connection was lost. 
 
While trying to reconnect to the Virtual machine az140-dc-vm11 >> Connect >> Bastion - it's throwing an error 'Connection Error'. It was working fine till Task 3 all of the sudden it was throwing the error.  If the issue is related to the Firewall or NSG then detailed instructions need to be provided in the instructions.

![ConnectionError](https://user-images.githubusercontent.com/92770552/151392153-ca2522ee-54eb-4c82-958d-5bd3e23c2314.png)

![Targetmachineunreachable](https://user-images.githubusercontent.com/92770552/151392318-e4e42f2a-cd01-4dae-9287-221c16f8ea10.png)

InboundPolicy
![inboundpolicy](https://user-images.githubusercontent.com/92770552/151392234-79051212-414b-4902-ac65-9dd7abe6d966.png)

Disabled the Firewall but it still throws the error.

![firewallprofile_false](https://user-images.githubusercontent.com/92770552/151392929-b2b3a907-309e-4784-ac0d-7ce37b7a51c1.png)

**Comment by polichtm** [comment]
Hi Parameswari,
Just to confirm - are you referring to these steps?

#### Task 4: Configure Azure Virtual Desktop application groups

1. Within the Remote Desktop session to **az140-dc-vm11**, in the web browser window displaying the Azure portal, search for and select **Azure Virtual Desktop** and, on the **Azure Virtual Desktop** blade, select **Application groups**.
1. On the **Azure Virtual Desktop \| Application groups** blade, note the existing, auto-generated **az140-21-hp1-DAG** desktop application group, and select it. 
1. On the **az140-21-hp1-DAG** blade, select **Assignments**.
1. On the **az140-21-hp1-DAG \| Assignments** blade, select **+ Add**.
1. On the **Select Azure AD users or user groups** blade, select **az140-wvd-pooled** and click **Select**.
1. Navigate back to the **Azure Virtual Desktop \| Application groups** blade, select **+ Add**. 

If so, there is no correlation between these steps and inbound connectivity via Bastion. In addition, none of these steps deal with any modifications to OS-level firewall.

If you experience unexplained connectivity issues, I'd suggest following https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/rdp 

In addition, you might want to check Azure Service Health.

Pls let us know if these suggestions do not resolve the issue you ran into

rgds
Marcin

**Comment by ParamRamki** [comment]
Hi Marcin,

Thanks for your email.

The issue is I’m not able to connect to the VM az140-dc-vm11. The steps I mentioned is where I got stuck during the lab (as you have mentioned it is not related to the exact error)  and kicked out of the virtual desktop. It is keep throwing 'connection error'.

I will check the Azure health report and I can provide more detailed screenshots soon.

Thanks
Param



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by polichtm** [comment]
Hi Param,
are you the only person in the class who is running into this issue?
rgds
Marcin

**Comment by ParamRamki** [comment]
Hi Marcin,

Right now, I’m the only person using the lab, not sure about others, whereas I found the same error posted by another user in MS Q/A.

https://docs.microsoft.com/en-us/answers/questions/219485/azure-bastion-connection.html

Thanks
Param

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by polichtm** [comment]
Hi Param,
I'm not sure I'm following. Are you an MCT?
rgds
Marcin

**Comment by ParamRamki** [comment]
Hi Marcin,

I'm from the Q/A team.

Thanks!


Sincerely,
Param

_______________________________

Custom Cybersecurity Solutions, LLC

CustomCyber.com<http://customcyber.com/>

Ph:1(562) 653-6593

“There’s no one solution fits all”

________________________________

**Comment by polichtm** [comment]
Not reproducible - closing...
