### ISSUE TITLE
Lab 04L01, Remove-CimInstance returns error

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#16]
# Module: 4
#### Step: 16

PS C:\Windows\system32> Get-CimInstance -ComputerName $servers -Class Win32_UserProfile | Where-Object { $_.LocalPath.split('\')[-1] -eq $userName } | Remove-CimInstance
Remove-CimInstance : The WS-Management service cannot process the request. The WMI service or the WMI provider returned an unknown error: HRESULT 0x80070020 
At line:1 char:128
+ ... ct { $_.LocalPath.split('\')[-1] -eq $userName } | Remove-CimInstance
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Win32_UserProfi...10-30082327...):CimInstance) [Remove-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070020,Microsoft.Management.Infrastructure.CimCmdlets.RemoveCimInstanceCommand
    + PSComputerName        : az140-21-p1-0

**Comment by polichtm** [comment]
Hi Ning,
Unfortunately I cannot reproduce this. Have you tried to run this command locally (without the ComputerName parameter) to verify whether it runs as expected?
rgds
Marcin

**Comment by ningweinw** [comment]
My AADDS test environment has been removed. I will report it again if this error recurs in the future

**Comment by polichtm** [comment]
Appreciated...
rgsd
Marcin
