### ISSUE TITLE
Lab 01L01, ADDS, VNet name not set during DC creation

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#17]
# Module: 1
#### Step: 1

VNet "az140-adds-vnet11" does not exist. The default name is: adVNET
Instruction for DC creation should include VNet name to overwrite the default

**Comment by polichtm** [comment]
Hi Ning
It appears that you are not using the parameters file - as instructed. Pls make sure to follow the instructions:

On the Edit parameters blade, select Load file, in the Open dialog box, select \\AZ-140\AllFiles\Labs\01\az140-11_azuredeploydc11.parameters.json, select Open, and then select Save.

rgds
Marcin
