### ISSUE TITLE
No host, exercise 1, Task 5: Verify the deployment of the Azure Virtual Desktop host

### ISSUE THREAD

**Issue by TheRealDeomax** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#175]
# Module: 02 Implement a WVD Infrastructure
#### Step: 3

Description of issue

There's no single host under 'Session hosts' in step 3.

Repro steps:

1.  Task 1: I connected to az140-dc-vm11 and created a new subnet 'hp3-subnet' 10.0.3.0/24
2.  Task 2: I created an empty as described in step 5
3.  Task 3: Ran the template to create a Win10 enterprise system
4.  Task 4: Add an azure vm running win10 hosts to the host pool.  Step 1 ran the AVD agent and boot loader onto the new vm from task 3, az140-24-p3-0.  Installed the az modules in step 3 .. 8: install agent and bootloader. No where do I see the step to add a new host to the pool for 'az140-24-hp3'
5.  check for single host.  NONE

**Comment by polichtm** [comment]
Are you the only one in your class who's running into this issue?
Unfortunately I'm not having much luck reproducing this behavior
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
