### ISSUE TITLE
Configure Conditional Access policies for WVD (AD DS)

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#179]
# Module: 03
#### Step: 02

Description of issue

UI has changed. Instructions need to be modified to reflect the current UI.

![image](https://user-images.githubusercontent.com/12164329/158918182-de0f0abd-ba5d-4d69-8d11-9f44db264558.png)

Identity Protection is in the 'Protect' section, not 'Manage' as instructed.

**Comment by polichtm** [comment]
updated
rgds
Marcin
