### ISSUE TITLE
Lab 01L01, DC VM name not set during creation

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#18]
# Module: 1
#### Step: 1

VM name az140-dc-vm11 does not exist. The default DC VM name is: adVM.
The DC creation instruction should include the setting for VM name to overwrite the default

**Comment by polichtm** [comment]
Hi Ning
It appears that you are not using the parameters file - as instructed. Pls make sure to follow the instructions:

On the Edit parameters blade, select Load file, in the Open dialog box, select \\AZ-140\AllFiles\Labs\01\az140-11_azuredeploydc11.parameters.json, select Open, and then select Save.

rgds
Marcin
