### ISSUE TITLE
Lab 01L01, ADDS, DC VM account credential not specified in the creation step

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#19]
# Module: 1
#### Step: 3

The DC VM credential should be included in the instruction for creation

**Comment by polichtm** [comment]
Hi Ning
It appears that you are not using the parameters file - as instructed. Pls make sure to follow the instructions:

On the Edit parameters blade, select Load file, in the Open dialog box, select \\AZ-140\AllFiles\Labs\01\az140-11_azuredeploydc11.parameters.json, select Open, and then select Save.

rgds
Marcin
