### ISSUE TITLE
microsoft.compute not registerd by default for new azurepass subscription. so add this step to be sure

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#2]
# Module: 01
#### Step: 04

For a new tenant with an azurepass subscription the microsoft.compute resourse is not registered by default if never installed a vm. So the ps commands to query the amount of available vcpu does not return result. After registering the resource it is ok. So please add a command to register microsoft.compute or have them verified from the portal.
[az140labmod1issue.pdf](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/files/6676219/az140labmod1issue.pdf)

**Comment by polichtm** [comment]
updated
rgds
Marcin
