### ISSUE TITLE
LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md unable to increase quotas due to high usage

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#207]
# Module: 00
#### Step: 06

Description of issue

I have tried several regions and it fails due to high usage in Eastus, Eastus2, Uksouth, southeastasia.

Anyone have any luck in other regions?

I am teaching this on monday next week,
![image](https://user-images.githubusercontent.com/24426530/162170535-17e752bd-e635-470b-b264-6b6d0503a179.png)

![image](https://user-images.githubusercontent.com/24426530/162170210-f50cd0b4-9104-43b9-923b-1e4d08868de6.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
have you considered submitting a support ticket?
rgds
Marcin

**Comment by dpapkin** [comment]
> Hi David, have you considered submitting a support ticket? rgds Marcin

Hi

I was just wondering if anyone had some suggestions for alternate reginos for Azure passes that had good capacity based on their experience.. thats all

**Comment by molenaar** [comment]
Here also lots of problems with increasing quotas. It was succesfull in Australia East, however Australia East don't support deployment of Host Pools.... ;-(

**Comment by molenaar** [comment]
Are there any default locations that work on Azure Sponsorship pass? The only locations you are able to try to increase are the US locations. They fail so you need to enter a support request. 
West Europe doesn't provide any VMs needed for this course. 

We have activated new subscriptions but still no luck. 

Support isn't responding and students have huge delays for this course this week!

Is there a plan b?

**Comment by polichtm** [comment]
Hi Marcel,
for the list of Azure regions in scope of the Azure Pass offering, pls refer to https://azure.microsoft.com/en-us/regions/offers/
If none of the Europe-based regions are available, I gather you'll need to try other regions. In my experience, as long as the quota increase requests are "reasonable", the turnaround is rather quick (hours)
rgds
Marcin

**Comment by polichtm** [comment]
Hi Marcel,
while I definitely see the value of this discussion, this is not the ideal forum for them - pls continue on the MCT forum instead.
Let me know if I can assist further
rgds
Marcin
