### ISSUE TITLE
Lab02  Deploy host pools and session hosts by using the Azure portal (AD DS) Deployment failed 

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#208]
# Module: 00
#### Step: 05

Description of issue
Deployment Fails. Click here for details
Exception occurred while joining Domain 'adatum.com'. It fails Create or Update Virtual Machine Extension. Says conflict

It does create the 2 VM and the Host pool.

One thing I noticed is that The DC doesnt have Domain FW applied. If no Azure, I would disable the NIC and renable. This usually fixes this issue

![image](https://user-images.githubusercontent.com/24426530/162413445-848b4e9b-9157-4470-ae52-82f94818e7c9.png)

![image](https://user-images.githubusercontent.com/24426530/162413060-44ba7002-816e-43a8-8955-693b3023bb75.png)

![image](https://user-images.githubusercontent.com/24426530/162412743-9309412d-b118-4133-99a0-a2768daaa795.png)

![image](https://user-images.githubusercontent.com/24426530/162412080-5374d66d-41d3-4455-a0f4-e673d9f720ba.png)

![image](https://user-images.githubusercontent.com/24426530/162411800-6cbff931-ea8f-4f90-9996-66acd9311725.png)

![image](https://user-images.githubusercontent.com/24426530/162411659-94e83e02-54ec-42be-9161-4f52a33840f7.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
are you using the most recent version of lab instructions? 
What are you seeing in the VM extension logs on the Azure VM where the domain join is failing?
rgds
Marcin

**Comment by dpapkin** [comment]
> Hi David, are you using the most recent version of lab instructions? What are you seeing in the VM extension logs on the Azure VM where the domain join is failing? rgds Marcin

Hi Marcin, good to hear from you.
Yes, using latest. I had pasted the screenshots of the logs.

I just tried again,  failed  . "VMExtensionProvisioningError. "message": "VM has reported a failure when processing extension 'joindomain'. Error message: \"Exception(s) occured while joining Domain 'adatum.com'\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot "
    }

Her eis teh logs from the vm that failed.

"code": "ComponentStatus/JoinDomainException for Option 3 meaning 'User Specified'/failed/1",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "ERROR - Failed to join domain='adatum.com', ou='OU=WVDInfra,DC=adatum,DC=com', user='student@adatum.com', option='NetSetupJoinDomain, NetSetupAcctCreate' (#3 meaning 'User Specified'). Error code 1355"
    },
    {
        "code": "ComponentStatus/JoinDomainException for Option 1 meaning 'User Specified without NetSetupAcctCreate'/failed/1",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "ERROR - Failed to join domain='adatum.com', ou='OU=WVDInfra,DC=adatum,DC=com', user='student@adatum.com', option='NetSetupJoinDomain' (#1 meaning 'User Specified without NetSetupAcctCreate'). Error code 1355

![image](https://user-images.githubusercontent.com/24426530/162442179-8e90be39-2ca5-42e5-b1cd-3c69d0873e8a.png)

**Comment by polichtm** [comment]
Hi David,
would you mind trying to perform the join manually using the same credentials?
rgds
Marcin

**Comment by dpapkin** [comment]
hi

i went into the windows 10 vm powershell  and used add-computer and it said , domain not contactble , i also used the gui System- advanced properties  and gives same error, but nslookup adatim.com foes resolve  but not with a 10.x.x.x IP address

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by polichtm** [comment]
Hi David,
this seems to point to a DNS issue - is the virtual network configured to use the VM hosting the domain controller as the DNS server? Btw. I assume you meant adatum.com....
rgds
Marcin

**Comment by dpapkin** [comment]
What would I check?

YEs, adatum.com

Thx

David P
________________________________

**Comment by dpapkin** [comment]
[cid:f5017322-ceea-4d53-a224-39830fa645ea]

[cid:f5a0a1f7-c39b-4dea-ad42-a77bf30d5737]


Hi,

I went to the vnet and changed it to use custom dns 10.0.0.4

This fixed it.

DId I miss something in the instructions?

David


________________________________

**Comment by polichtm** [comment]
Hi David,
as far as I recall, this should've been configured automatically as part of the template deployment. I don't recall running into this issue before
rgds
Marcin
