### ISSUE TITLE
aka.ms link should point to GitHub Pages, not the repo.

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#209]
I think the shortlink, https://aka.ms/az140labs, should point to the labs in GitHub Pages, not the Repo.

Just like, for example, https://aka.ms/az400labs

Can this be changed?

**Comment by polichtm** [comment]
Work in progress...
rgds
Marcin

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by polichtm** [comment]
Populated https://microsoftlearning.github.io/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/ 
rgds
Marcin

**Comment by polichtm** [comment]
updated README.md to include the link to lab instructions
