### ISSUE TITLE
Lab 02L01 ADDS, need to wait for host pool creation before creating RemoteApp

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#21]
# Module: 2
#### Step: 7

The Note should say: wait for the deployment to complete
If the hosts are not deployed and running, applications cannot be added. This operation requires a running host to pull the application info

**Comment by polichtm** [comment]
updated
