### ISSUE TITLE
LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md: Edge install really necessary?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#214]
# Module: 01
##### Step: 02

Description of issue

In **Exercise 2,Task 4, Steps 2-3**, we are directed to install **Edge** on VM **az140-dc-vm11**, and I am getting a report that:  _"...Microsoft edge is already installed in the virtual machine. Not sure why we had to reinstall microsoft edge thru internet explorer..."_ 

Given the process described in those steps appears to be exactly what we would need to do if we were using an older VM OS that did not have **Edge** installed by default (as, I believe Server 2016 does not) ...I wonder if these are instructions that are now to be considered obsolete if the default Window Server DC image that gets created now (as opposed to when course was originally written) now has **Edge** installed by default?

Then again, I see a similar issue in the past was fixed with instructions updates that left the 'download and install edge' step in the instructs - but just clarified that the browser install process was for education purposes, which is also understandable:  https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/commit/8b480975a116b275c3d48b2ff726b9535d984565

I wonder if we might want to do the same thing in this .md file?  i.e., if the install is desired for educational purposes, just add in a similar type of clarification?   

It may also be possible that the latest version of **Edge** is always going to be desired in case there are any old rendering bugs in version of **Edge** that comes stock on the DC VM once it is deployed to Azure.  If that's the case - might be good to drop a short clarifying note in those steps as well....just to reassure a student who already sees **Edge** installed that they are not wasting time, and **do** need to execute that download & install?

**Comment by polichtm** [comment]
The current version of the lab uses Windows Server 2019, which does not include Microsoft Edge. 
rgds
Marcin
