### ISSUE TITLE
CreateADForest Deployment Failure

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#216]
#### Step: 03

When attempting to deploy the VM running an AD DS domain controller, the template fails to deploy with the error "VM has reported a failure when processing extension 'CreateADForest'

![image](https://user-images.githubusercontent.com/48496971/175114200-c99cd472-3b1a-4a0f-ba7d-6d726eeb7c08.png)

**Comment by polichtm** [comment]
This is resolved - pls give it another try
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
