### ISSUE TITLE
Issue in LAB_03L01_Configure_Conditional_Access_policies_for_AVD_ADDS

### ISSUE THREAD

**Issue by Rakshithac183** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#223]
# Module: AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop
##### Step: 04

Description of issue

While performing step 4: Point 3, the **Azure Virtual Desktop** entry is not showing up in the **cloud apps** blade.

Repro steps:

4. On the **New** blade, configure the following settings:

   - In the **Name** text box, type **az140-31-wvdpolicy1**
   - In the **Assignments** section, select the **Users or workload identities** option, in the **What does this policy apply to?** drop-down list, ensure that **Users and groups** is selected, in the **Select Users and groups** section, select the **Users and groups** checkbox, on the **Select** blade, click **aduser5**, and then click **Select**.
   - In the **Assignments** section, click **Cloud apps or actions**, ensure that in the **Select what this policy applies to** switch, the **Cloud apps** option is selected, click the **Select apps** option, on the **Select** blade, select the checkbox next to the **Azure Virtual Desktop** entry, and click **Select**. 

Please refer the below snapshot:

![Azure not displaying cloud apps](https://user-images.githubusercontent.com/103628971/207840048-4550cc65-8d79-4d8b-b93e-2d5fc74d12de.png)

Additionally, I even verified that all the previous steps are performed correctly and also tried searching by using individual search terms **Virtual** and **Desktop**, yet nothing was displayed to select.

**Comment by polichtm** [comment]
appreciate the feedback - investigating
rgds
Marcin

**Comment by polichtm** [comment]
This is resolved
rgds
Marcin
