### ISSUE TITLE
AZ-140 Mod 1 Lab - Prepare for deployment of Azure Virtual Desktop - ADDS

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#224]
# Module: 01
## Lab/ 01

1. Quota increase now requires MFA challenge.
2. BS size quota requires support ticket in eastus
3. Network Provider fails on first deployment of Domain Controller, Should register that like the Compute provider.
4. Template deployment fails "screen capture" about extension and login domain error.

![error-adds-deployment-az140m1](https://user-images.githubusercontent.com/30813190/208469532-bd932a31-ad3e-4520-b716-8d8de1795040.png)

**Comment by MikeVeschi** [comment]
Exercise 1 Task 2 Step 3

Might be better to use this template as the github one in the text is 6 months old and I don't think its linked to it's updates  after the MSLearn move

https://learn.microsoft.com/en-us/samples/azure/azure-quickstart-templates/modules-active-directory-new-domain-0.9/

I did not get WINRM error with this template

I was able to deploy with uploading parameters file mentioned.

Also deploys LB with NAT for RDP which might better as it eliminates need to deploy bastion which eats credits.

**Comment by polichtm** [comment]
Hi Mike,
appreciate the suggestions. Regarding the use of Bastion, this is required to address brute force attacks that were affecting students implementing the AZ-140 labs
rgds
Marcin

**Comment by polichtm** [comment]
Hi Mike,
this has been resolved
rgds
Marcin
