### ISSUE TITLE
Unable to find VM image "Windows 10 Enterprise multi-session, Version 2004 + Microsoft 365 Apps"

### ISSUE THREAD

**Issue by kumud-sharma** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#225]
Module: LAB_L02

 

Lab: LAB_02L01_Deploy_host_pools_and_session_hosts_with_the_Azure_portal_ADDS.md

 

Exercise: Exercise 1: Implement an Azure Virtual Desktop environment in an AD DS domain

 

Task: Task 3: Manage the Azure Virtual Desktop host pool session hosts

 

Step: 06.

 

 

Description of issue:

While performing step 06, the VM image "Windows 10 Enterprise multi-session, Version 2004 + Microsoft 365 Apps" wasn't available in Azure.

 

 

Repro steps:

 

6. On the Virtual Machines tab of the Add virtual machines to a host pool blade, specify the following settings and select Review + create (leave others with their default settings):

 
<img width="570" alt="imagestep6" src="https://user-images.githubusercontent.com/33771500/209512915-aa89da54-22de-4bef-9692-0d91c6a05f80.png">

 

 

Please refer the snapshots below.
<img width="177" alt="Azureimage" src="https://user-images.githubusercontent.com/33771500/209512835-bb2b27c8-b915-47a5-b4bd-4f36a26c1d97.png">

 

 

Request you to assist the earliest.

**Comment by polichtm** [comment]
This is already updated - pls refer to https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Instructions/Labs/LAB_02L01_Deploy_host_pools_and_session_hosts_with_the_Azure_portal_ADDS.md 
rgds
Marcin
