### ISSUE TITLE
Unable to deploy ARM template

### ISSUE THREAD

**Issue by kumud-sharma** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#226]
Module: LAB_02L03
 
Lab: LAB_02L03_Deploy_host_pools_and_hosts_with_ARM_templates_ADDS.md
 
Exercise: Exercise 1: Deploy Azure Virtual Desktop host pools and hosts by using Azure Resource Manager templates
	 
Task: Task 2: Deploy an Azure Virtual Desktop host pool and hosts by using an Azure Resource Manager template

Step: 02.
 
Description of issue:

While performing step 02, the given ARM template is not deploying.
 
Repro steps:
 
2. From your lab computer, in the same web browser window, open another web browser tab and navigate to the GitHub Azure RDS templates repository page [ARM Template to Create and provision new Azure Virtual Desktop hostpool](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/CreateAndProvisionHostPool).

Please refer to the snapshots below.
![image](https://user-images.githubusercontent.com/33771500/209825943-886047d5-a562-415c-b64f-2e477c65ed57.png)

![image](https://user-images.githubusercontent.com/33771500/209826895-eb2d624c-2af0-4b02-a343-57a9177503ff.png)

	 
Request you to assist the earliest.

**Comment by polichtm** [comment]
Pls post the details of the error message
rgds
Marcin

**Comment by kumud-sharma** [comment]
Hi, Marcin
I have tried again today it gets deployed now.

Thanks and regards
Kumud Sharma

**Comment by polichtm** [comment]
Hi Kumud, 
just to confirm - the deployment completes successfully?
rgds
Marcin

**Comment by polichtm** [comment]
Pls let us know if you need any additional assistance
rgds
Marcin
