### ISSUE TITLE
Unable to run the automation workbook script in LAB_05L01_Implement_autoscaling_in_host_pools_ADDS

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#228]
# Module: 5
#### Step: 13

Description of issue
Hello, I am unable to run the script to create an automation account with the given script CreateOrUpdateAzAutoAccount.ps1
The script times out after 30 minutes with the following error message.

![image](https://user-images.githubusercontent.com/47213023/212723988-62cda178-19c0-4274-9e2f-b4be91de1549.png)

Tried running the script using PowerShell 7 and PowerShell 5.1, but still no luck.
Can you please suggest a fix here?

Thanks, and Regards,
Junaid Hussain.

**Comment by polichtm** [comment]
Hi Junaid,
pls comment out the following lines (97-99) in the CreateOrUpdateAzAutoAccount.ps1 script and recreate the Automation account

#	'Az.Compute'
#	'Az.Resources'
#	'Az.Automation'

The instructions have been updated accordingly
rgds
Marcin
