### ISSUE TITLE
Unable to run the Query in LAB_05L01_Implement_autoscaling_in_host_pools_ADDS

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#229]
# Module: 5
#### Step: 05

Description of issue
When trying to run the query in the log analytics workspace, I am getting the following error with TimeStampLocal = TimeStamp_s.
Can you please assist here?

Thanks, and Regards.
![image](https://user-images.githubusercontent.com/47213023/213155376-8ce32a82-275e-4034-a5dd-7ae8e3e1046a.png)

**Comment by junnhssn** [comment]
Unable to trigger the autoscale scheduler condition, I think we should specify how the autoscale condition can be met. Due to this we are unable to perform the exercise 2

![image](https://user-images.githubusercontent.com/47213023/213436524-624b4c75-1c10-4178-b97a-8f9800caea56.png)

**Comment by polichtm** [comment]
Hi Junaid,
could you clarify what you mean by "Unable to trigger the autoscale scheduler condition"?
This appears to be working as intended. You should be seeing two out of three hosts being automatically stopped/deallocated
rgds
Marcin

**Comment by polichtm** [comment]
Unfortunately I'm not able to reproduce the issue you're running into with the KQL query - this works for me as intended.  
![image](https://user-images.githubusercontent.com/10284906/213602653-fcebdc17-edc1-4b7e-9f24-0eb79cd828f5.png)


rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
