### ISSUE TITLE
Lab 02L03, path name of lab files

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#23]
# Module: 2
#### Step: 5

The lab file path: \\AZ-140\AllFiles\Labs\02\az140-23_azuredeployhp23.parameters.json, may give the impression of a network file. Instead, can we make it clear, the file path should point to the local lab file directory?

**Comment by polichtm** [comment]
Hi Ning,
appreciate the suggestion, but this is not a network path (which would start with \\) - we leave to students/instructor to decide where they want to download the lab files
rgds
Marcin
