### ISSUE TITLE
MFA Issue in LAB_03_Ex2_Configure_Conditional_Access_policies_for_AVD_ADDS

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#231]
# Module: 03
#### Step: 04

Description of issue
aduser5 still asks for MFA 

This happened with most of the students in my class

<img width="185" alt="image" src="https://user-images.githubusercontent.com/24426530/228753709-1c4f4e7d-c70e-4996-a4a3-2652db9c4f0f.png">

<img width="708" alt="image" src="https://user-images.githubusercontent.com/24426530/228754265-015362b2-3ff8-4500-a42b-034c177cfb9c.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/24426530/228754328-5a27e905-a399-4bc0-bc88-3edafc46416b.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/24426530/228754538-d5a9e970-4836-4953-8b76-fe842053faa2.png">

**
Conditional Access Policy
<img width="154" alt="image" src="https://user-images.githubusercontent.com/24426530/228754627-27265fd3-e0ff-4c7d-9015-b95b56d67c91.png">
**
<img width="155" alt="image" src="https://user-images.githubusercontent.com/24426530/228754728-dead859e-873e-4e31-a2e9-700c7c3ae7cf.png">

<img width="307" alt="image" src="https://user-images.githubusercontent.com/24426530/228754866-603eb7c7-0c0c-4989-b9f7-beeaa588ffd0.png">

<img width="225" alt="image" src="https://user-images.githubusercontent.com/24426530/228754940-c19ac8d5-211d-4b5c-b311-bf0f31a0f2e1.png">

<img width="141" alt="image" src="https://user-images.githubusercontent.com/24426530/228755060-bb8c16de-cbb4-41b5-b359-f42b9fe77367.png">

<img width="121" alt="image" src="https://user-images.githubusercontent.com/24426530/228755139-21878c57-8f41-497d-ae6a-8683fb544898.png">

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
the What if functionality of Azure AD CA should give a clear indication of the expected outcome - did you give this a try?
rgds
Marcin

**Comment by dpapkin** [comment]
Hi Marcin, 

Several of the people STILL asks for MFA, the instructions say it shouldn't because it is Hybrid joined,

<img width="516" alt="image" src="https://user-images.githubusercontent.com/24426530/228998566-2354a436-cdb6-486d-b523-d51d765eb2b2.png">

What is "What if functionality of Azure AD CA " ? where to find it? thanks

**Comment by polichtm** [comment]
Hi David,
pls refer to https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/what-if-tool 
rgds
Marcin

**Comment by polichtm** [comment]
Hi David,
pls let me know if you run into this problem again - this seems to work for me without any issues
rgds
Marcin

**Comment by dpapkin** [comment]
Hi,

20% of the class had this issue.

David Papkin

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dpapkin** [comment]
Will see what happens next class

David

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
