### ISSUE TITLE
Images expiring

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#245]
# Module: All
## Lab: All

Description of issue
The images used for the VMs in this lab (**20H2**) reach **End of servicing** on **5/9/2023**. 

We need to change to 21H2 or 22H2 (or Win 11)!

https://learn.microsoft.com/en-us/windows/release-health/release-information#windows-10-current-versions-by-servicing-option

**Comment by polichtm** [comment]
Hi Eric,
appreciate the feedback - investingating
rgds
Marcin

**Comment by polichtm** [comment]
addressed
