### ISSUE TITLE
LAB_01L01: active-directory-new-domain QuickStart template fails

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#247]
- Module 1: Plan a AVD Architecture
- Lab 1: Prepare for deployment of Azure Virtual Desktop (AD DS)
- Exercise 1: Deploy an Active Directory Domain Services (AD DS) domain
- Task 2: Deploy an Azure VM running an AD DS domain controller by using an Azure Resource Manager QuickStart template
- step 8

Deployment of the template hosted at the repo URL provided in the linked line fails for two reasons.

> https://github.com/az140mp/azure-quickstart-templates/tree/master/application-workloads/active-directory/active-directory-new-domain

https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/094c7370a0575acd96df3def04fbd47ce7f3f3f1/Instructions/Labs/LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md?plain=1#L133

When following lab instructions as currently written, the below error is observed stating that the specified image version is not found:

![2-c4000642-becc-4738-ba3c-982c5a02b55e](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/134323425/532bb1a0-e7bb-49d3-8948-2ff6bfadef81)

Editing line 200 of the template to read `"version": "latest"` corrects this issue.

https://github.com/az140mp/azure-quickstart-templates/blob/7989e12ffbedc77dca94b4875f0057e1de7ee911/application-workloads/active-directory/active-directory-new-domain/azuredeploy.json?plain=1#L195-L201

However, the template also fails to deploy for a second reason: template JSON files linked to by the top-level template are not found. The `_artifactsLocation` parameter must be set to `https://raw.githubusercontent.com/az140mp/azure-quickstart-templates/master/application-workloads/active-directory/active-directory-new-domain/` to correct this.

These failures could be resolved by updating the template used or by adding additional steps to the instructions. A template version that deploys when otherwise following the existing instructions was tested here:

https://github.com/SkillableMG/azure-quickstart-templates/tree/az140-latest/application-workloads/active-directory/active-directory-new-domain

Repro steps:

1. Perform the above-referenced task.

**Comment by polichtm** [comment]
updated
rgds
Marcin
