### ISSUE TITLE
Lab steps

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#248]
Do we know if the change to CloudSlice for the labs means the lab steps will be re-written? A lot of the labs have the same issues now with accuracy as they did 18 months ago.

It's worse now with the change from AAD to Entra ID. 

I don't want to submit a huge PR if the labs are being re-written in a months time.

**Comment by polichtm** [comment]
Hi Steve
The CloudSlice considerations are being investigated.
As far as the Entra ID related changes are concerned, are you expecting the need for any modifications beyond those related to the actual rebranding?
rgds
Marcin

**Comment by WigF1** [comment]
Hey Marcin,

There's lots of steps that are different other than just branding.

**Comment by polichtm** [comment]
Hi Steve,
Appreciate the feedback. This is being addressed...
rgds
Marcin

**Comment by polichtm** [comment]
Hi Steve,
this has been addressed. Pls let us know if you have any other concerns regarding this topic.
rgds
Marcin
