### ISSUE TITLE
Typo in content

### ISSUE THREAD

**Issue by SMG0927** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#249]
On URL: https://learn.microsoft.com/en-us/training/modules/implement-manage-fslogix/1-introduction?source=learn
Under 'Manage user environments and apps for Azure Virtual Desktop' module 'Implement and manage FSLogix' -
There's a typo in the section 'Learning Objectives', third bullet, where it incorrectly says 'Install FXLogix.' It must be corrected to say 'Install FSLogix.'

![Screenshot1](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/74800964/ab07131f-5a00-4c9b-8c0c-5c0d9d27d0f4)
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by WigF1** [comment]
That's nothing to do with the lab content - you need to raise the issue with Microsoft Learn by using the link on the page.

**Comment by polichtm** [comment]
Pls follow the suggestion from Steve
rgds
Marcin
