### ISSUE TITLE
LAB_02L05: "Security type: Standard" required for `az140-25-hp4`  VM

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#250]
- Lab - Create and manage session host images (AD DS)
- Exercise 1: Create and manage session host images
- Task 5: Provision a Azure Virtual Desktop host pool by using a custom image
- steps 5-8

Virtual machine settings configured in the above steps for the `az140-25-hp4` host pool require the "Security type: Standard" setting for compatibility with the image used. Sometime this year, Azure portal updated the default setting to "Security type: Trusted launch" when configuring VMs.

The following commit added this setting to the configuration for `az140-21-hp1` VMs in LAB_02L01: https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/commit/7188a33fe975d8a37e35feb3974093576d3fb25c

If the "Trusted launch" setting is not changed, the deployment will fail at step 10 following the above-referenced steps, with message "Use of TrustedLaunch setting is not supported for the provided image".

Repro steps:

1. Complete Task 5 as written

**Comment by polichtm** [comment]
Investigating...
rgds
Marcin

**Comment by polichtm** [comment]
This will be addressed through image updates (to address #245)
rgds
Marcin
