### ISSUE TITLE
L01 Deploying AZ VM using ARM template results in template parameter error

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#269]
Lab 1: Prepare for deployment of Azure Virtual Desktop (AD DS)
Exercise 1: Deploy an Active Directory Domain Services (AD DS) domain
Task 3: Deploy an Azure VM running Windows 10 by using an Azure Resource Manager QuickStart template
Step 3: From the PowerShell session in the Cloud Shell pane, run the following to deploy an Azure VM running Windows 10 that will serve as a client into the newly created subnet:

Description of issue:

Following the steps exactly as written on [Task 3: Deploy an Azure VM running Windows 10 by using an Azure Resource Manager QuickStart template](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Instructions/Labs/LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md#task-3-deploy-an-azure-vm-running-windows-10-by-using-an-azure-resource-manager-quickstart-template) results in a parameter template error [p1]. It appears some wires may have been crossed when switching from Azure AD to Entra ID, and some parameters may need to be reviewed as it is consistently failing.

[p1]

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/94069201/da6b3f7e-f158-4dfe-bac2-ee6a9c23ceae)

**Comment by polichtm** [comment]
updated
rgds
Marcin
