### ISSUE TITLE
Lab 03L01, MFA registration UI is different

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#27]
# Module: 3
#### Step: 2

The latest MFA registration UI presents a pulldown list to choose between authentication phone, app, office phone. Please update the steps.

**Comment by polichtm** [comment]
Hi Ning,
what specifically would you want to see in the instructions?
rgds
Marcin

**Comment by ningweinw** [comment]
The instructions: "_This will automatically redirect your browser to the Microsoft Authenticator page.
On the Microsoft Authenticator page, click the link I want to set up a different method_...." are no longer valid.

Below is the current MFA registration UI. Can the instruction be updated accordingly?

![image](https://user-images.githubusercontent.com/43491290/123280348-49a0e500-d53b-11eb-9a8f-1433aec58d28.png)

**Comment by polichtm** [comment]
updated
