### ISSUE TITLE
Issue with Windows image

### ISSUE THREAD

**Issue by Noztra** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#270]
# Module: 1
#### Step: 5

Description of issue
You can't deploy using the templates:
az140-11_azuredeploycl11a.json
az140-11_azuredeploycl11a.parameters.json

It shows the following error:
New-AzResourceGroupDeployment: 5:19:46 PM - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'az140lab0101vmDeployment' is not valid according to the validation procedure. The tracking id is '155e98f2-f94f-4e77-9683-099fc03e83fd'. See inner errors for details.
New-AzResourceGroupDeployment: 5:19:46 PM - Error: Code=InvalidParameter; Message=The following list of images referenced from the deployment template are not found: Publisher: MicrosoftWindowsDesktop, Offer: Windows-10, Sku: 22h2-pro, Version: latest. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images.

Repro steps:

1. Upload the two template files to the Azure CLI
1. Run the command provided:
$resourceGroupName = 'az140-11a-RG'
$location = (Get-AzResourceGroup -ResourceGroupName $resourceGroupName).Location
New-AzResourceGroupDeployment `
  -ResourceGroupName $resourceGroupName `
  -Location $location `
  -Name az140lab0101vmDeployment `
  -TemplateFile $HOME/az140-11_azuredeploycl11a.json `
  -TemplateParameterFile $HOME/az140-11_azuredeploycl11a.parameters.json

**Comment by polichtm** [comment]
This has been updated
rgds
Marcin
