### ISSUE TITLE
az140-42_azuredeploycl42.json needs updated OSVersion

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#271]
#### Step: 02

Description of issue
\\AZ-140\AllFiles\Labs\04\az140-42_azuredeploycl42.json returns an invalid template error [p1], which appears to be an issue with azuredeploycl42.json's 91st line, windowsOSVersion: "22h2-pro" -- no such offer exists. Switching it to Win10-22h2-pro resolves the issue.

[p1]

![image-1](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/94069201/78737e6c-785c-4689-bb16-164d23038bd2)

**Comment by polichtm** [comment]
updated
rgds
Marcin
