### ISSUE TITLE
Issue with Entra ID P2

### ISSUE THREAD

**Issue by kmtrading** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#272]
# Module: 3
#### Step: 12

The ENTERPRISE MOBILITY + SECURITY E5 license no longer exists and the Microsoft Entra Premium P2 license requires a bank card. It is no longer possible to have a trial.

**Comment by WigF1** [comment]
Any feedback or updates on this issue? At the moment, it is not possible to complete this lab.

**Comment by polichtm** [comment]
Updated instructions to provide more clarity regarding this consideration
rgds
Marcin
