### ISSUE TITLE
Issue with the link to the GitHub Azure RDS template repository page.

### ISSUE THREAD

**Issue by dhananjaygr** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#273]
# Module 2: Implement an AVD Infrastructure
#### Step: 1

It appears there is an issue with the provided link to the GitHub Azure RDS templates repository page. The ARM template is not deploying correctly, with deployment exceeding 1 hour and encountering parameter issues from the nested template.

**Comment by polichtm** [comment]
Pls let us know if you're still running into this issue - and, if so, provide the requested details
rgds
Marcin
