### ISSUE TITLE
Lab - Deploy host pools and session hosts by using the Azure portal (AD DS)

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#274]
Exercise 1, Task 4

Description of issue

Adding apps UI has changed. Lab steps need a change. Icon index and path are on a separate tab.

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/27dd0c37-8ff3-4aa2-8ad8-fb34058f7b31)

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/b69499fa-a04a-4a5e-b7f7-261dab4faea4)

**Comment by polichtm** [comment]
Hi Steve,
addressed
rgds
Marcin
