### ISSUE TITLE
Lab - Implement and manage storage for AVD (AD DS)

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#275]
Exercise 1, Task 3, Step 9

Description of issue

The UI no longer shows Active Directory and Configured.

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/e07a74f8-4396-4431-af10-e363bde72fa5)

It now shows as per below

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/d5ed8b93-a417-4b7d-9b99-6e7e91799ae5)

**Comment by polichtm** [comment]
Hi Steve,
resolved
rgds
Marcin
