### ISSUE TITLE
Lab 0301 - Find and replace

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#279]
Lab 3 needs amending. It seems every instance of Azure Active Directory was replaced. Even though the software is still called 'Azure Active Directory Connect'.

References to the application need to be reverted back to Azure Active Directory Connect.

**Comment by polichtm** [comment]
Hi Steve,
considering that this change is bound to happen at some point, we added a note at the beginning of the lab providing more info regarding this discrepancy
rgds
Marcin
