### ISSUE TITLE
LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md, remove AzureAD module

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#282]
# Module: LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md
### Task 2: Configure AD DS UPN suffix

The AzureAD module has been deprecated. We should remove references to it from labs.

Remove steps 6, 7, and 8.

Replace the PowerShell code in step 9 with

````powershell
$aadDomainName = (Get-AzTenant -TenantId $tenantId).DefaultDomain
````

We should also replace the next section with New-MgUser (which would require installing PowerShell 7 on the DC). _I've got the start of instructions for this, but it is Friday afternoon. :-) I'll finish them and post them next week._

**Comment by mctfabrice** [comment]
hello
i will deliver the az-140 and I have some questions
You are talking about the old azure ad module
in fact now its ms graph module

so my question in this lab are all the module working correctly

also what about the azure subscription
I will work with goeploy las hosting lab and I saw in the module that we have to ask to the student to
subside a free Azure account with their MasterCard or visa card ?????? 
imposible is there a solution 
tks

**Comment by polichtm** [comment]
Hi Craig - appreciate the input. The updates to the modules are in progress...

Hi Fabrice - the current instructions should work, but I'd encourage you to step through the labs before you deliver the training sessions. It's not clear to me what you're referring to regarding credit cards - what specifically are they required for in your case?

rgds
Marcin

**Comment by polichtm** [comment]
This module is outside of the scope of the future enhancements
rgds
Marcin
