### ISSUE TITLE
Implement and manage storage for AVD (AD DS) - Issue

### ISSUE THREAD

**Issue by SkillableKA** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#289]
Lab: Implement and manage storage for AVD (AD DS)
Exercise : 1 
Task : 3 
Step : 3

Description of issue:
Error running the following commands in PowerShell as instructed in the lab:

$subscriptionId = (Get-AzContext).Subscription.Id
$resourceGroupName = 'az140-22-RG'
$storageAccountName = (Get-AzStorageAccount -ResourceGroupName $resourceGroupName)[0].StorageAccountName

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/169093291/bb5cfe6b-50fa-4648-b7f8-37a0a07d204c)

The only workaround I have found is to run the commands in CloudShell. The instructor has reported this has occurred at multiple places inside the lab.

Repro steps:

1. Ran through prior labs to reach the reported error step
2. Ran commands as instructed and failed
3. Tried in PS 7.x and failed
4. Ran varieties of Connect-AzAccount

**Comment by polichtm** [comment]
Instructions have been updated to account for this issue. Pls let us know if you're still running into this issue
