### ISSUE TITLE
LAB_02L01_Deploy_host_pools_and_session_hosts_with_the_Azure_portal_ADDS - Preferred app group changes

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#292]
# Module: 02
#### Task: 02

Description of issue

A recent change (first week of June, 2024 it seems) means that from now on, you will no longer see a mix of SessionDesktop and RemoteApps when both are assigned to the same hostpool.

This page details the change:
https://learn.microsoft.com/en-us/azure/virtual-desktop/preferred-application-group-type

The important note mentions this. 

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/a3f722f1-ac06-42bf-a905-3f41471b13e6)

It's also something that is being rolled out to all tenants globally.

So, for my students that chose Aus East, we can't see both any longer after completing Task 2. 

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/f895cca2-a9bd-4eb8-9ac6-b8db357242b0)

I had one student who (luckily) chose East US and the changes haven't made it across the pond yet. They still see both:

![image](https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/assets/12164329/57a384ca-93e9-403b-8174-5d7990fe38c5)

I don't know how best to approach this change. We either need to add steps to have students change the preferred app group type and then refresh the remote desktop after they have saved the change. This would likely be done after Task 2 or in Task 2. 

The other alternative is to remove verbiage around "you now see both" and instead, have student subscribe with aduser1 to see the session desktop and then aduser5 to see the remoteapps. 

Either way, things have to change in the lab.

**Comment by WigF1** [comment]
Hello?

**Comment by polichtm** [comment]
Hi Steven
the focus has been in recent weeks on developing a new set of labs based on Entra ID (without dependencies on AD DS/Entra DS) - these account for the new functionality you are referencing. We'll be addressing these issues next
rgds
Marcin

**Comment by polichtm** [comment]
updated
rgds
Marcin
