### ISSUE TITLE
Username and Passwords still hardcoded in the labs

### ISSUE THREAD

**Issue by karenhowells** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#295]
# Module: 01
#### Step: 06

Hard coded instructions for username and password in template

1.  When you upload the template   az140-11_azuredeploydc11.parameters  it's still got **Student** and **Pa55w.rd1234** hard coded.  

"adminUsername": {
      "value": "Student"
    },
    "adminPassword": {
      "value": "Pa55w.rd1234"
    },

Can I suggest that the adminPassword is removed and users are left to create their own passwords, in line with all the other Github labs for other courses where it is not there.  I had a problem on my course today that one of the students had issues with bastion, it was really flaky, so ended up creating a public ip - with default settings - (yes I know that's not ideal and I didn't know he had done it!) but no sooner had he connected to his vm using public ip, it was compromised because that is a known username and password and network scanners know the public ip address ranges that Azure use and the passwords printed in lab instructions and templates  I think all instances of typing Student and Pa55w.rd1234 should be removed!!  

Also may be a good idea to change the name of the dc parameters file - so many of my students were trying to use the cl file when deploying domain controller and ending up with it on the wrong virtual network, because the parameters file for client doesn't mention the virtual network!!

**Comment by WigF1** [comment]
I would say that the student opening RDP was the foolish move. :)

With regards the admin password, if we let students choose their own password for something as fundamental as the Domain Admin the chaos would be unabounded. As it is, students struggle to manage the credentials. 

On this course, students need an email / password for the ALH, an email / password for the Azure Pass, an email / password for the Entra tenant users a la aduser1 / aadsyncuser. I don't think we should have them choose yet another password.

It's not just the initial deployment of the DC, it's every deployment. They would have to specify the correct domain join password in lab 0201,0203,0204,0205,0402. If they mess it up, that's 30 minutes down the drain and they have to start again as the last couple of tasks are always the DSC / JoinDomain.

And all this would be avoided as long as students know **never** to add a public IP. I think that's a better long-term mechanism for the course deliveries.

**Comment by polichtm** [comment]
Hi Steve and Karen,
Appreciate the feedback - it is indeed the tradeoff between security and usability (as is frequently the case). We're trying to find the optimal balance between the two. Lab participants can obviously affect that balance by not following directions (or choosing their own, non-secure passwords). We'll be looking at alternatives that hopefully will address the issues that both of you highlighted
rgds
Marcin
