### ISSUE TITLE
LAB_03L01_Configure_Conditional_Access_policies_for_AVD_ADDS requires Entra Trial

### ISSUE THREAD

**Issue by PurvesG2** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#297]
# Module: 09 Manage security for Azure Virtual Desktop
#### Step: 12 	On the Activate blade, click Free trial in the MICROSOFT ENTRA ID P2 

Description of issue
Students must use an Entra 30-day trial for this lab.
Students cannot sign up for a Entra Trial without a credit card
We cannot have them using a personal credit card which will start being billed after the trial

Solution: Provision the students with an M365 Tennant with trail licensing as in the MD-102 then 
have the students activate The Azure Pass against the Pre-Provisioned M365 Tennant

**Comment by WigF1** [comment]
See #272

**Comment by polichtm** [comment]
Correct - pls refer to #272 
rgds
Marcin
