### ISSUE TITLE
https://raw.githubusercontent.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/master/Instructions/Labs_EntraID/07_LAB_15_01_Create_custom_session_host_images_by_using_image_templates_StandAlone.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#298]
# Module: 00
#### Step: 05

Description of issue

**Exercise 1/Task 8/Step 5:**  After making the required changes to the Subnet, there is no 'Add' option only (Save or Cancel) - presumably should change 'Add' to 'Save'.

**Comment by polichtm** [comment]
updated
rgds
Marcin
