### ISSUE TITLE
https://raw.githubusercontent.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/refs/heads/master/Instructions/Labs_EntraID/03_LAB_41_01_Implement_monitoring_by_using_Azure_Virtual_Desktop_Insights.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#299]
# Module: 00
#### Step: 02

Description of issue

**Exercise 1/Task 2/Step 2:** In table, 'Virtual network name' appears as just 'Name':
![image](https://github.com/user-attachments/assets/778e961f-f5eb-4ef0-b3ef-b00986b419ff)

**Comment by polichtm** [comment]
updated
rgds
Marcin
