### ISSUE TITLE
create a note that after request for increase vcpu limits you can continue whit next steps

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#3]
# Module: 01
#### Step: 08

The note is now
Note: Quota increase requests within this range of vCPUs are typically completed within a few hours.

The student does not have to wait for hours to continue with the next steps in this task (no need for the extra vcpu to create adds) . so maybe make this clear in the note?

**Comment by polichtm** [comment]
updated
rgds
Marcin
