### ISSUE TITLE
06_Lab_11_01: Implement Azure Private Link for Azure Virtual Desktop

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#302]
#### Task 7

Description of issue

Task 6, Steps 42 and 43 (and the note that exists above them) do not need to exist as this is the last lab in the sequence and all resources will be removed upon ending the lab instances.

![image](https://github.com/user-attachments/assets/a9061e54-d3bf-4e6e-8a09-3319e1e6468b)

Task 7 in this lab does not need to exist for the same reason.

![image](https://github.com/user-attachments/assets/6b494aa7-5e04-4b84-ba34-d30b372edae7)

There are no other labs that use the same AVD environment. This is the last of the 6 labs in the launch sequence. If someone launches the optional lab 7, they receive a totally different environment.

**Comment by polichtm** [comment]
updated
rgds
Marcin
