### ISSUE TITLE
LAB_02L02 Typo  AzFilesHybid.zip should be  AzFilesHybrid.zip 

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#35]
LAB_02L02_Implement_and_manage_storage_for_AVD_ADDS.md
Exercise 1: Configure Azure Files to store profile containers for Azure Virtual Desktop
Task 3: Enable AD DS authentication for the Azure Storage account

Within the Remote Desktop session to az140-dc-vm11, open another tab in the Microsoft Edge window, navigate to the Azure Files samples GitHub repository, download [the most recent version of the compressed **AzFilesHybid.zip** PowerShell module, and extract its content into C:\Allfiles\Labs\02 folder (create the folder if needed).

Should be AzFilesHybrid.zip

**Comment by polichtm** [comment]
updated
