### ISSUE TITLE
LAB_02L02_Implement_and_manage_storage_for_AVD_ADDS; Task 3 instructions 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#36]
# Module: LAB_02L02_Implement_and_manage_storage_for_AVD_ADDS
#### Step: 01

Description of issue

Within the Remote Desktop session to az140-cl-vm11a, in the Microsoft Edge window, in the Azure portal, on the blade displaying the properties of the storage account you created in the previous task, in the vertical menu on the left side, in the **Settings** section, select **Configuration**.

**_Option is not available in Settings Currently. Was located in the File shares settings page (may need to rewrite steps)_**

Repro steps:
https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Instructions/Labs/LAB_02L02_Implement_and_manage_storage_for_AVD_AADDS.md#task-3-enable-azure-ad-ds-authentication-for-the-azure-storage-account

**Comment by polichtm** [comment]
updated
