### ISSUE TITLE
Azure ADDS: Add should be Create

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#37]
# Module: 0`1
#### Step: 1

Description of issue
+Add should be +Create

Repro steps:

Task 2: Deploy an Azure AD DS instance by using the Azure portal

"From your lab computer, in the Azure portal, search for and select Azure AD Domain Services and, from the Azure AD Domain Services blade, select + Add. This will open the Create Azure AD Domain Services blade."

In my blade there is only a '+ Create' button.

**Comment by polichtm** [comment]
Unfortunately this particular interface item has been inconsistent across different blades and, what's more impactful, it has been changing overtime. We are planning to address this once these issues are remediated. In the meantime, pls inform students at the beginning of the course that they might encounter + New, + Add, or + Create across different blades. Fortunately, in this case, the options are rather intuitive
rgds
Marcin
