### ISSUE TITLE
Confusing instructions on creating virtual network

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#38]
# Module: 01
#### Step: 04

Description of issue
"4. On the Create virtual network blade, specify the following settings and select OK (**leave others with their existing values**)"

During the lab an address space (10.0.0.0/24) already exists (or is prefilled). Also an subnet 'aadds-subnet' already is prefilled
It appears to be very confusing to both myself and other students.  Especially because it writes 'leave others with their existing values'

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Would you mind clarifying what specifically you find confusing - and what specifically would you want to change in order to minimize potential confusion? 
The purpose of the phrase "leave others with their existing values" is to indicate that you should change only the settings which are explicitly referenced in the instructions.
rgds
Marcin

**Comment by velden** [comment]
Thank you. 
Well instructions write you should add aan new vnet az140-aadds-vnet11a
Once you start doing that it already has a 10.0.0.0/24 address specified. 
Also it has a 'aadds-subnet' prefilled (10.0.0.0/24)

I think (but I'm learning not knowing) that it should be **replaced** with the ip-ranges specified in the instructions
(10.10.0.0/16 for the address range and 10.10.0.0/24 for the subnet). But 'replacing' implies changing existing values.
Because of the 'leave others with their existing values' it seems you shouldn't not touch those prefilled values.

I may be wrong. Perhaps you can just try and see how it looks and if it seems confusing to you.

**Comment by polichtm** [comment]
Would you mind taking a screenshot of what you're looking at and including it in this thread?
rgds
Marcin

**Comment by velden** [comment]
I would have done it earlier if I knew it was possible.

As I'm getting behind in this course because of other issues in the labs (see issue #39) I'm not able to fully reproduce this issue. I usually follow the labs step by step so I think it should be reproducible. But it should be the exact steps and not changing the network afterwards, because it seems the window is slightly different then.

![2021-07-14 14_25_55-AZ-140 _ Microsoft Teams](https://user-images.githubusercontent.com/4172150/125621861-b139c7a1-4c1b-4779-95f0-07c3eb608f64.png)

**Comment by polichtm** [comment]
appreciate the clarification. Updated...
rgds
Marcin
