### ISSUE TITLE
The LAB is very badly designed.

### ISSUE THREAD

**Issue by win-scripter** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#39]
The instructions between AZ ADDS and ADDS are quite confusing.

* For each lab please use numbers.
* The instructions for lab do not exist for AZ ADDS setup.

The students are wasting time re-doing the labs which they are not familiar with.

**Comment by polichtm** [comment]
Appreciate the feedback.
Pls note that it would be your responsibility as a trainer to let students know which labs they should run. 
Could you clarify what you mean by "The instructions for lab do not exist for AZ ADDS setup"?
rgds
Marcin

**Comment by velden** [comment]
I can elaborate on that: Once you've chosen the path of Azure AD DS you eventually arrive at the lab for working with arm templates. (Lab - Deploy host pools and hosts by using Azure Resource Manager templates) 
Look at the prerequisites of that lab. It requires the AD DS path, not the Azure AD DS.
_- The completed lab Prepare for deployment of Azure Virtual Desktop (AD DS)
- The completed lab Deploy host pools and session hosts by using the Azure portal (AD DS)_

And there is no such lab for the Azure AD DS. 

After hours of doing labs it's quite annoying to find out you can't continue.

**Comment by polichtm** [comment]
Appreciate the feedback. 
Trying to duplicate the very same labs for the two different scenarios would considerably increase development and maintenance efforts. 
We're working on providing more clarity regarding the intended approach to the two separate lab scenarios. 
In the meantime, pls note that the lab dependencies are clearly defined at the beginning of each lab.
rgds
Marcin

**Comment by win-scripter** [comment]
> Appreciate the feedback.
> Pls note that it would be your responsibility as a trainer to let students know which labs they should run.
> Could you clarify what you mean by "The instructions for lab do not exist for AZ ADDS setup"?
> rgds
> Marcin

I am not a trainer. I am a student doing the labs in the course.

**Comment by polichtm** [comment]
This forum is intended for MCTs - pls refer too the Readme.md - https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop
rgds
Marcin
