### ISSUE TITLE
Lab - Create and configure host pools - Instruction set Pub IP  = yes Port setting missing

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#4]
# Module: 02
#### Step: 03

In the instructions Public IP is set to YES. Not sure if we need this later. If not it should be NO if Yes maybe also specify the port that needs to be open.

**Comment by polichtm** [comment]
Would you mind clarifying why this should be set to NO?
In addition, pls provide the module name, exercise number, task number, and step number you're referring to
rgds
Marcin

**Comment by koenraadhaedens** [comment]
The setting is default NO > "By default, access to the virtual machine is restricted to sources in the same virtual network, and traffic from Azure load balancing solutions. Select None to confirm, or choose to allow traffic from the public internet to one of these common ports."
Do not see any best practice to open ports to the public internet for the host pool vm's. This is only needed in special circumstances. If you want to enable AVD RDP shortcut (still in preview) it is better to create NSG on VNET level.

**Comment by polichtm** [comment]
appreciate the clarification. This is a valid point - the content has been updated accordingly
rgds
Marcin
