### ISSUE TITLE
Reorder Parameters listed in the instructions

### ISSUE THREAD

**Issue by ankulbhardwaj** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#41]
# Module: 02
## Lab/Demo: 02L1-Deploy_host_pools_and_session_hosts_with_the_Azure_portal_ADDS
###Exercise :01
#### Step: 03

Description of issue
The order in which the values are specified in the portal. 
For example : 
AD domain join UPN is asked first and then Specify OU path. 

Solution 

Pls update the values as per my attached screenshot as several students have highlighted this as a challenge and are getting confused. 
![values](https://user-images.githubusercontent.com/86134788/126857593-e14210db-60ec-4385-890a-39a303fdee31.PNG)

**Comment by polichtm** [comment]
updated
