### ISSUE TITLE
Unable to create ResourceGroupDeployment

### ISSUE THREAD

**Issue by wingkchan** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#43]
# Module: 1
#### Step: 3: From the PowerShell session in the Cloud Shell pane, run the following to deploy an Azure VM running Windows 10 that will serve as a Azure Virtual Desktop client and join it to the Azure AD DS domain:

Description of issue:  After uploading the "az140-11_azuredeploycl11a.json" and "az140-11_azuredeploycl11a.parameters.json", running the script.  running the commands came back with error

New-AzResourceGroupDeployment: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Repro steps:

1. Uploaded both .json files to /Home

2.  When run the script, it came back with error:  
New-AzResourceGroupDeployment:
Line |
   3 |    -Location $location `
     |    ~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'Location'.

3. Tried leaving out the" -Location $location".  error returned:
New-AzResourceGroupDeployment: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by polichtm** [comment]
Pls provide a copy of the template you are using (the one you uploaded)
rgds
Marcin

**Comment by wingkchan** [comment]
Thanks Marcin, The templates that i am using are from the Labs\01\ folder:

\Allfiles\Labs\01\az140-11_azuredeploycl11a.json
https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Allfiles/Labs/01/az140-11_azuredeploycl11a.json

\Allfiles\Labs\01\az140-11_azuredeploycl11a.parameters.json
https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Allfiles/Labs/01/az140-11_azuredeploycl11a.parameters.json

Thanks

**Comment by polichtm** [comment]
I'm aware of their original location. 
I'd like to take a look at a copy of the template you are uploading to Cloud Shell (pls copy and paste its content into your response)
rgds
Marcin

**Comment by wingkchan** [comment]
Hi Marcin,

I simply downloaded these 2 files from the Lab\01 folder and then uploaded them to cloud shell without making any changes.  So what I uploaded is exactly what is on the repository.  I believe those files are 2000+ lines, so it might be hard to upload them here.   thanks.
wing

**Comment by polichtm** [comment]
Hi Wing,
the first 20 lines might suffice. 
rgds
Marcin

**Comment by wingkchan** [comment]
Hi Marcin, 

Thank you for your suggestion!  I right-click on the .json files, and chose "Save link as".  I thought I was saving the files, but in fact it wasn't.  I uploaded the files with the correct content and I was able to deploy the VM successfully.  thank you for your help.

regards
wing

**Comment by polichtm** [comment]
Hi Wing,
you're welcome
rgds
Marcin
