### ISSUE TITLE
Lab2 task3 step 20. Not clear that you need to use the azure portal on the cl vm

### ISSUE THREAD

**Issue by koenraadhaedens** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#5]
# Module: 01
#### Step: 20

Th instruction says "Within the Remote Desktop session to az140-cl-vm11a, search for and select Azure Virtual Desktop and, on the Azure Virtual Desktop blade, select Application groups."

It should be "Within the Remote Desktop session to az140-cl-vm11a **open edge and go to the azure portal**, search for and select Azure Virtual Desktop and, on the Azure Virtual Desktop blade, select Application groups.

**Comment by polichtm** [comment]
Pls provide the full module name, exercise number, task number, and step number you're referring to
rgds
Marcin

**Comment by koenraadhaedens** [comment]
LAB_02L01_Create_and_configure_host_pools_and_session_hosts_AADDS.md
Lab - Create and configure host pools and session hosts (Azure AD DS)
Exercise 1: Configure an Azure Virtual Desktop environment
Task 3: Configure Azure Virtual Desktop application groups
step 20
"Within the Remote Desktop session to az140-cl-vm11a, search for and select Azure Virtual Desktop and, on the Azure Virtual Desktop blade, select Application groups."

**Comment by polichtm** [comment]
Appreciate the clarification. Is there a reason you wound want to start another web browser window and sign in to the Azure portal again? This already happened in step 1 of that task
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
