### ISSUE TITLE
Host pool location may not be same as resource location

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#50]
# Module: 2
#### Step: 2

For host pool creation, the description of Location says: "the name of the Azure region into which you deployed resources in the first exercise of this lab". This is not accurate, the location here is for host pool metadata, may not be same as the resource location a user chose earlier

**Comment by polichtm** [comment]
updated
