### ISSUE TITLE
Workspace location may not be same as resource location

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#51]
# Module: 2
#### Step: 3

Description of workspace location: the name of the Azure region into which you deployed resources in the first exercise of this lab
This is the metadata location, may not be same as the location for resource creation. For example, if we use southeastasia for resources, this location cannot be used for workspace

The same error appears in some other labs too, please review and update

**Comment by polichtm** [comment]
updated
