### ISSUE TITLE
Storage creation instruction needs update for RA-GRS

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#52]
# Module: 2
#### Step: 7

Storage creation wizard has changed, it no longer displays RA-GRS, but the following:
![image](https://user-images.githubusercontent.com/43491290/131340718-71780c15-0fd5-46a6-9c07-e7959411c9ac.png)

**Comment by polichtm** [comment]
updated
