### ISSUE TITLE
LAB_02L03, wrong Boot Diagnostics string

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#53]
# Module: 2
#### Step: 5

After loading az140-23_azuremodifyhp23.parameters.json, the Boot Diagnostics string shows wrong value. This error did not exist before loading the parameter file
![image](https://user-images.githubusercontent.com/43491290/131351347-797fcc93-2a1e-4524-8eac-e6c40321d9c9.png)

**Comment by polichtm** [comment]
updated
