### ISSUE TITLE
clean up instructions

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#55]
# Module: LAB_04L01_Implement_and_manage_AVD_profiles_AADDS
#### Step: 00

Description of issue: There should be resource clean up instructions at the end of this lab as this is the last lab of "Azure AD DS" and there is no further lab in this course which depends on the output of this lab.

**Comment by polichtm** [comment]
updated

**Comment by azharkhuwaja** [comment]
thanks, I submitted four issues in AZ 304 lab instructions too but no response yet.
