### ISSUE TITLE
Lab_02L05 Teams and Edge are preinstalled in VM, clarify the purpose of installing them again

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#57]
# Module: 2
#### Step: 14, 16

Both Teams and Edge are preinstalled in the VM image, please clarify in the lab instructions the purpose of performing installation again

**Comment by polichtm** [comment]
updated
