### ISSUE TITLE
Lab_02L05 QuotaExceeded error when creating host pool

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#58]
# Module: 2
#### Step: 10

QuotaExceeded error is returned when creating the host pool
The quota set for D2sv3 is 20, however there are already 10 D2sv3 VMs till the step to create host pool
The previous labs, ie. Lab 02L03 and 02L04, should include steps to delete VMs

**Comment by polichtm** [comment]
updated
