### ISSUE TITLE
Lab_03L01 Start-ADSyncSyncCycle error

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#59]
# Module: 3
#### Step: 2

Need to run the following command first, otherwise Start-ADSyncSyncCycle throws error of "not recognized"
Import-Module -Name "C:\Program Files\Microsoft Azure AD Sync\Bin\ADSync"

**Comment by polichtm** [comment]
updated
