### ISSUE TITLE
Lab_04L02 Role assignment needs to be set on Storage account, not File share

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#63]
# Module: 4
#### Step: 7-10

If role assignment is set on File share az140-42a-msixvhds, there will be error during creating MSIX app, reporting that the session host fails to access the virtual desk.

Such role assignment needs to be set on Storage account, the MSIX app can be created successfully

**Comment by polichtm** [comment]
updated
