### ISSUE TITLE
LAB_04L01, newly added code to configure 'az140-21-p1-1', 'az140-21-p1-2' throws error

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#64]
# Module: 4
#### Step: 25

The code to install FSLogix on 'az140-21-p1-1', 'az140-21-p1-2' throws error:
Copy-Item : The network path was not found
At line:4 char:1
+ Copy-Item -Path $localPath\Release -Destination $remotePath -Filter ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand

The code cannot form the $remotePath using the $server array, but needs to loop through the server array

**Comment by polichtm** [comment]
updated
