### ISSUE TITLE
LAB_02L03 Instruction not clear regarding copying the registration token

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#66]
# Module: 2
#### Step: 3

Many learners were confused with this step, and didn't know the token has already been copied into clipboard.

Please make the instruction clearer, example: the registration token is copied into Windows' clipboard, paste (ie. Ctrl-V key) it into notepad or a similar tool

**Comment by polichtm** [comment]
updated
