### ISSUE TITLE
Confusing instructions LAB_02L05

### ISSUE THREAD

**Issue by paulschnack** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#68]
# Module: 02
#### Step: 06

Description of issue

The instruction "Wait for the deployment to complete but instead proceed to the next exercise. The deployment might take about 10 minutes" is confusing. I'm pretty sure it should be "wait until the deployment is complete before proceeding to the next exercise".

**Comment by polichtm** [comment]
updated
rgds
Marcin
