### ISSUE TITLE
Difficult folder-structure to train. Can we, please create subfolders for the lab*.md files b ADDS resp. AADDS tracks (my students are rebelling).

### ISSUE THREAD

**Issue by GitHub-Soliman** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#69]
# Module: 00
#### Step: 00

Description of issue
Moin Moin.
My students are confused by the labs and the needed order.
How about, creating a subfolder ADDS resp. AADDS within "https://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop/blob/master/Instructions/Labs" and sorting the according lab*.md-files into them.
_Tschüß,
__Michael.
P.S.: I know, that the files are accordingly suffixed, but it is still difficult for them to click the according next one, if You have 10 students and have to govern them, in order to obtain the correct files.
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Michael,
appreciate the suggestion. Pls refer to the information in the ReadMe in this repo:

The labs comprise two separate tracks, depending on the identity provider you decide to use.

Active Directory Domain Services (AD DS). This track consists of the following labs:

LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md
LAB_02L01_Deploy_host_pools_and_session_hosts_with_the_Azure_portal_ADDS.md
LAB_02L02_Implement_and_manage_storage_for_AVD_ADDS.md
LAB_02L03_Deploy_host_pools_and_hosts_with_ARM_templates_ADDS.md
LAB_02L04_Deploy_and_manage_host_pools_and_hosts_with_PowerShell_ADDS.md
LAB_02L05_Create_and_manage_session_host_images_ADDS.md
LAB_03L01_Configure_Conditional_Access_policies_for_AVD_ADDS.md
LAB_04L01_Implement_and_manage_AVD_profiles_ADDS.md
LAB_04L02_Package_AVD_applications_ADDS.md
LAB_05L01_Implement_autoscaling_in_host_pools_ADDS.md
Azure Active Directory Domain Services (Azure AD DS). This track consists of the following labs:

LAB_01L01_Prepare_for_deployment_of_AVD_AADDS.md
LAB_02L01_Create_and_configure_host_pools_and_session_hosts_AADDS.md
LAB_02L02_Implement_and_manage_storage_for_AVD_AADDS.md
LAB_04L01_Implement_and_manage_AVD_profiles_AADDS.md

rgds
Marcin
