### ISSUE TITLE
Lab 1, AADDS, different message for "Network configuration issue detected..."

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#8]
# Module: 1
#### Step: 2

Instead of "Network configuration issues detected...", Azure now shows the following:
![image](https://user-images.githubusercontent.com/43491290/122876448-1c500d80-d368-11eb-8cdd-1e3d665ac20e.png)

**Comment by polichtm** [comment]
updated
